site_name: Serie
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:    # Palette toggle for light mode
    - scheme: default
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Foreword: index.md
  - Fundamental Programming:
      - "Stanford CS106L":
              - 2. Types and Structs: "Fundamental Programming/CS106L/types-and-structs.md"
              - 3. Initialization and References: "Fundamental Programming/CS106L/initialization-and-references.md"
              - 4. Streams: "Fundamental Programming/CS106L/streams.md"
      - "UC Berkeley CS61A":
          - "CS61A Note": "Fundamental Programming/CS61A/note.md"
  - Database Systems:
    - "CMU 15-445":
        - 1. Introduction: "Database Systems/15-445/introduction.md"
  - Misc:
        - "Data Structures [Junmin Lee]": "Misc/dsa-junmin.md"